version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      angular:
        patterns:
          - '@angular/*'
          - '@angular-devkit/*'
          - 'ng-packagr'
      tooling:
        patterns:
          - '*'
        exclude-patterns:
          - '@angular/*'
          - '@angular-devkit/*'
          - 'ng-packagr'
