import { _IdGenerator } from '@angular/cdk/a11y';
import {
  booleanAttribute,
  Component,
  computed,
  forwardRef,
  inject,
  input,
  model,
  numberAttribute,
  signal,
} from '@angular/core';
import { type ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

/**
 * Stars to pick from, built on native radio buttons: arrow keys move between
 * them, forms and screen readers see a radio group, and CSS fills and previews
 * the stars. Name the group with `aria-label` or `aria-labelledby`.
 *
 * ```html
 * <div nuiRating aria-label="Rate this recipe" [(value)]="stars"></div>
 * <span nuiRating readonly [value]="4.3"></span>
 * ```
 *
 * Read-only, it shows any fraction ("Rated 4.3 out of 5"). It works with Signal
 * Forms (`[formField]`), reactive forms and `ngModel`.
 */
@Component({
  selector: '[nuiRating]',
  providers: [
    { provide: NG_VALUE_ACCESSOR, useExisting: forwardRef(() => NuiRating), multi: true },
  ],
  host: {
    class: 'nui-rating',
    '[attr.role]': 'readonly() ? "img" : "radiogroup"',
    '[attr.aria-label]': 'readonly() ? readonlyLabel()(value() ?? 0, max()) : null',
    '[attr.data-readonly]': 'readonly() ? "" : null',
    '[style.--_value]': 'value() ?? 0',
    '[style.--_max]': 'max()',
    '(focusout)': 'onTouched()',
  },
  template: `
    @if (readonly()) {
      <span class="nui-rating-display" aria-hidden="true"></span>
    } @else {
      @for (star of stars(); track star) {
        <label class="nui-rating-item">
          <input
            class="nui-rating-input"
            type="radio"
            [name]="name()"
            [value]="star"
            [checked]="value() === star"
            [disabled]="isDisabled()"
            [attr.aria-label]="starLabel()(star)"
            (change)="choose(star)"
            (click)="toggle(star, $event)"
          />
          <span class="nui-rating-star" aria-hidden="true"></span>
        </label>
      }
    }
  `,
})
export class NuiRating implements ControlValueAccessor {
  /** The rating, or null for none. Bind with `[(value)]`. */
  readonly value = model<number | null>(null);
  readonly max = input(5, { transform: numberAttribute });
  /** Shows the value, to any fraction, instead of asking for one. */
  readonly readonly = input(false, { transform: booleanAttribute });
  readonly disabled = input(false, { transform: booleanAttribute });
  /** Clicking the chosen star again clears the rating. */
  readonly clearable = input(false, { transform: booleanAttribute });
  /** Radio group name, shared by the stars. Generated by default. */
  readonly name = input(inject(_IdGenerator).getId('nui-rating-'));
  /** Accessible name of each star. */
  readonly starLabel = input<(value: number) => string>(
    (value) => `${value} ${value === 1 ? 'star' : 'stars'}`,
  );
  /** Accessible name when read-only. */
  readonly readonlyLabel = input<(value: number, max: number) => string>(
    (value, max) => `Rated ${value} out of ${max}`,
  );

  protected readonly stars = computed(() => Array.from({ length: this.max() }, (_, i) => i + 1));
  private readonly formDisabled = signal(false);
  protected readonly isDisabled = computed(() => this.disabled() || this.formDisabled());

  private onChange: (value: number | null) => void = () => undefined;
  protected onTouched: () => void = () => undefined;

  protected choose(star: number): void {
    this.value.set(star);
    this.onChange(star);
  }

  /**
   * A click on a star. On the star that is already chosen, it clears the rating:
   * `change` doesn't fire for it (the radio is already checked), and `click` comes
   * first otherwise, so the value here is still the one before the click.
   */
  protected toggle(star: number, event: MouseEvent): void {
    // Safari doesn't focus a radio it clicks; focused, the arrow keys go on from it.
    const input = event.currentTarget as HTMLInputElement;
    if (input.ownerDocument.activeElement !== input) input.focus({ preventScroll: true });
    if (this.clearable() && this.value() === star) {
      this.value.set(null);
      this.onChange(null);
    }
  }

  writeValue(value: number | null): void {
    this.value.set(value ?? null);
  }

  registerOnChange(fn: (value: number | null) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(disabled: boolean): void {
    this.formDisabled.set(disabled);
  }
}
